### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by DOGGOLOVER679** [edqx/amongus-protocol#29]
code:
import {
    AmongusClient,
    MasterServers,
    ColourID,
    HatID,
} from "amongus-protocol"

(async() => {
const server = MasterServers.EU[0];

const client = new AmongusClient({});

await client.connect(server[0], server[1], "weakeyes");

client.search();
//const game = await client.join();

//game.me.on("spawn", () => {
  //  game.me.setName("weakeyes");
  ///  game.me.setColour(ColourID.Black);
 //   game.me.setHat(HatID.Plague);
//});
})
Error:
internal/modules/cjs/loader.js:1031
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/..../amongus/node_modules/amongus-protocol/js/index.js
require() of ES modules is not supported.
require() of /home/...../amongus/node_modules/amongus-protocol/js/index.js from /home/...../amongus/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/..../amongus/node_modules/amongus-protocol/js/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/......./amongus/node_modules/amongus-protocol/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1031:13)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/......./amongus/index.js:39:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'ERR_REQUIRE_ESM'
}

Can anyone help me?

**Comment by edqx** [comment]
add `"type": "module"` to your `package.json`

**Comment by DOGGOLOVER679** [comment]
Ok ty 😄
